version: '3.8'

services:
  web:
    build: .
    volumes:
      - static:/opt/app/static
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - envs/db.env

  redis:
    image: redis:7.0.8-alpine

  celery-beat:
    env_file: envs/web.env
    build: .
    command: celery -A transaction_system beat
    depends_on:
      - db
      - redis
    restart: unless-stopped

  celery-worker:
    env_file: envs/web.env
    build: .
    command: celery -A transaction_system worker
    depends_on:
      - db
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static:/data/static
    depends_on:
      - web
    ports:
      - "80:80"

volumes:
  static:
  postgres_data:
